### ISSUE TITLE
Unable to install themes distribution

### ISSUE THREAD

**Issue by noldeni** [typo3-themes/themes_distribution#2]
I've tried to install the themes_distribution in a fresh install of TYPO3 6.2.15 with no success.
I went to "Extension Manager" and "Get preconfigured distribution" and clicked "Install" on the "Themes Distribution".
After some time the following errormessage is displayed:
![2015-12-11 10_12_10-typo3 themes test 2 typo3 cms 6 2 15](https://cloud.githubusercontent.com/assets/11617057/11753124/badbf850-a043-11e5-810f-cf90399bf0c7.png)
In Extension Manager i can see the following extensions:
- dyncss 0.7.8 (enabled)
- dyncss_less 0.7.5 (disabled)
- gridelements 3.2.0 (enabled)
- static_info_tables 6.2.1 (enabled)
- t3jquery 3.0.3 (enabled)
- theme_bootstrap 1.4.6 (disabled)
- theme_bootstrap_slate 1.1.3 (disabled)
- themes 2.5.0 (enabled)
- themes_distribution 0.1.3 (disabled)
- themes_gridelements 0.6.3 (enabled)
- yaml_parser 1.0.1 (enabled)

In another working installation I have dyncss and dyncss_less version 0.7.4.
I think the installation pulls the wrong version from ter.
I've also tried to install the extensions one by one. But that failed when installing theme_bootstrap. Will open an Issue on that also.
So for me there is no **easy** way of installing the Themes Distribution.

**Comment by kaystrobach** [comment]
This was a Problem with TER, please update your extension Version list via the get New extension Dialoge, this was fixed with a New Upload last wednesday ;)

----- Originale Nachricht -----
Von: Ingo Nolden notifications@github.com
Gesendet: 11.12.2015 - 20:35
An: typo3-themes/themes_distribution themes_distribution@noreply.github.com
Betreff: [themes_distribution] Unable to install themes distribution (#2)

**Comment by noldeni** [comment]
I can try this tomorrow but I think that will not work because I did the complete installation this morning.
So the extensionlist should be up to date.

**Comment by noldeni** [comment]
FYI: I managed to install the themes distribution on the same server on Dec. 3. without problems.

**Comment by kaystrobach** [comment]
Yes the Problem in TER occurred since DEC 1st until the 8th, if you updated ext list in this date range there might be errors.

I uploaded new versions around the 6th and Ter transformed dependencies from typo3 (lowercase) to TYPO3 uppercase ... This is causing your problem, so please update the extlist and try again. Works here perfectly.

----- Originale Nachricht -----
Von: Ingo Nolden notifications@github.com
Gesendet: 11.12.2015 - 23:11
An: typo3-themes/themes_distribution themes_distribution@noreply.github.com
Betreff: Re: [themes_distribution] Unable to install themes distribution (#2)

**Comment by noldeni** [comment]
Doesn't work for me!
**The package "dyncss_less" depends on "TYPO3" which is not present in the system.**

**Comment by kaystrobach** [comment]
I will retry next week.

----- Originale Nachricht -----
Von: Ingo Nolden notifications@github.com
Gesendet: 12.12.2015 - 14:07
An: typo3-themes/themes_distribution themes_distribution@noreply.github.com
Betreff: Re: [themes_distribution] Unable to install themes distribution (#2)
